apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  labels:
    app: logger
spec:
  selector:
    matchLabels:
      app: logger
  replicas: 1
  template:
    metadata:
      labels:
        app: logger
    spec:
      serviceAccountName: che-workspace
      containers:
        - name: logger
          image: quay.io/mvala/k8slograb:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /workspace_logs
              name: log-storage
      volumes:
        - name: log-storage
          emptyDir: {}
