kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv01
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/vda1/hostpath_pv"
