apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: che-workspace-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logs
subjects:
- kind: ServiceAccount
  name: che-workspace
  namespace: che-che