kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logs
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
